color: null
fieldLayouts:
  2009f073-384e-4274-90d7-e934f3dc47a6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-02-23T11:03:16+00:00'
            elementCondition: null
            fieldUid: 6522b3e9-975e-46f9-82c4-ca4fd89ef4b4 # BTW nummer
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 501cd86e-e03b-409e-a612-3915bd5334cf
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-23T11:03:16+00:00'
            elementCondition: null
            fieldUid: fdf11145-cf77-4635-a872-2b900223e4e8 # Straat en nummer
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 50d2a0a7-eb58-4034-a2cc-758051ba4cdb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-23T11:03:16+00:00'
            elementCondition: null
            fieldUid: 2008324f-13c7-4130-b879-5e3e2d272123 # Postcode
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 59feaa85-372b-4c24-9833-e024914015da
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-23T11:03:16+00:00'
            elementCondition: null
            fieldUid: 85833dac-d58f-4262-b34a-7fc21a74c548 # Plaats
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 29a726c5-f31d-44fb-9a76-cc8ec77f4ed4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-28T19:35:14+00:00'
            elementCondition: null
            fieldUid: b8ab75b6-fc56-40da-b011-dcfed847dd63 # Google Maps
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4a7d7474-2e78-459e-bebd-4bc23036ae77
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-23T11:03:16+00:00'
            elementCondition: null
            fieldUid: 8b68262e-6fe4-4dea-9563-543898f92f84 # Mailadres
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ce73a9b0-8036-42ec-b3ad-a409f4521c8d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-23T11:03:16+00:00'
            elementCondition: null
            fieldUid: e8402b03-d9a2-4670-9862-b5168dd5d4c5 # Telefoonnummer
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9dff07d4-0fa9-4811-9884-a9bb2fe5f847
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-28T18:22:44+00:00'
            elementCondition: null
            fieldUid: a0958a06-0e63-499a-99fe-ec51c95e9112 # Tonen
            handle: null
            includeInCards: false
            instructions: 'Zet deze knop aan om het kadertje met de witte boord te tonen.'
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: da74fc03-dc74-442a-9b1d-978df5e835f1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-28T18:19:43+00:00'
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\LightswitchFieldConditionRule
                  fieldUid: a0958a06-0e63-499a-99fe-ec51c95e9112 # Tonen
                  layoutElementUid: da74fc03-dc74-442a-9b1d-978df5e835f1
                  uid: 876a2a54-a72f-47c7-9c26-dbf2d3cde9ab
                  value: true
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 5d067db8-2536-4d07-a966-d4f807d19704 # Kader
            handle: null
            includeInCards: false
            instructions: 'Dit is het kadertje met de witte boord (om verlof in aan te geven)'
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8f4c92f7-0cad-463d-a62c-34674a006fc9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-23T11:03:16+00:00'
            elementCondition: null
            fieldUid: b396c5ad-4751-4f93-9fd4-678f8f04dc88 # Info
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1a96f985-7d65-4d40-b1d5-9658084d38aa
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: ee7bc746-9174-4b25-ba6b-768d4a011eb4
        userCondition: null
handle: info
hasTitleField: false
icon: null
name: Informatie
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
