color: null
fieldLayouts:
  44d5388d-ca81-434a-ac1a-276080465586:
    cardView:
      - 'layoutElement:355db1fa-c4f1-4c30-b027-2c772e449390'
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-20T18:58:19+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9ce08f84-39f7-44a4-83b5-67020a60e5b0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-20T18:59:43+00:00'
            elementCondition: null
            fieldUid: 22739330-272f-4214-be42-a5e7c7cd0978 # Tekst
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 355db1fa-c4f1-4c30-b027-2c772e449390
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: abb95164-4c46-4cf7-a57b-13354bac20e1
        userCondition: null
handle: infoNotice
hasTitleField: true
icon: null
name: Melding
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
