columnSuffix: null
handle: kader
instructions: null
name: Kader
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: ''
  ckeConfig: fdb5eef6-de84-4ce5-9d33-787bd5b8c792 # Simple
  createButtonLabel: null
  defaultTransform: null
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
