defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 4c7a80d6-0249-476d-95bf-c287d9c3dcdf # Titel
handle: menu
maxAuthors: 1
name: Menu
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primaire invoer-pagina'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  c44f25bd-e99c-4f49-87e4-1ac555445a3b: # Eskobar
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: menu
type: single
