defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 2b1b3dcb-0aea-4b32-b903-c03a0490bbc7 # Pagina
handle: tempPage
maxAuthors: 1
name: 'Tijdelijke pagina'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primaire invoer-pagina'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  c44f25bd-e99c-4f49-87e4-1ac555445a3b: # Eskobar
    enabledByDefault: true
    hasUrls: true
    template: _errors/temp.twig
    uriFormat: temp
type: single
